name: Fetch CJ Products

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:  # Allows manual triggering

jobs:
  fetch-products:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Verify Script Exists
        run: |
          echo "Checking for fetch_cj_products.py..."
          ls -R
          if [ ! -f "fetch_cj_products.py" ] && [ ! -f "scripts/fetch_cj_products.py" ]; then
            echo "❌ Error: fetch_cj_products.py not found in root or scripts/ directory!"
            exit 1
          fi

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Fetch Script
        env:
          API_URL: ${{ secrets.CJ_API_URL }}
          API_KEY: ${{ secrets.CJ_API_KEY }}
        run: |
          if [ -f "fetch_cj_products.py" ]; then
            python fetch_cj_products.py
          elif [ -f "scripts/fetch_cj_products.py" ]; then
            python scripts/fetch_cj_products.py
          else
            echo "❌ Error: fetch_cj_products.py not found!"
            exit 1
          fi
